version: '3'
services:
  app:
    container_name: prisma.app.mysql
    build: .
    restart: always 
    ports: 
      - "3000:3000"
    env_file: .env
    depends_on: 
      - prismadbpostgres

  prismadbmysql:
    container_name: prisma.db.mysql
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3306:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - prisma-db-mysql:/var/lib/prisma/mysql

volumes:
  prisma-db-mysql:
