version: '3'
services:
  app:
    container_name: prisma.app.mssql
    build: .
    restart: always 
    ports: 
      - "3000:3000"
    env_file: .env
    depends_on: 
      - prismadbpostgres

  prismadbmssql:
    container_name: prisma.db.mssql
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    command: /bin/bash ./entrypoint.sh
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "a1?%fkARF!24x"
      MSSQL_PID: Express
      ACCEPT_EULA: "Y"
    volumes:
      - prisma-db-mssql:/var/lib/prisma/mssql
      - ./libs/core/src/db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./libs/core/src/db/mssql/docker-db-init.sh:/db-init.sh
      - ./libs/core/src/db/mssql/testdb.sql:/db-init.sql

volumes:
  prisma-db-mssql: