version: '3'
services:
  app:
    container_name: prisma.app.postgres
    image: "prisma_postgres"
    build: .
    restart: always 
    ports: 
      - "3000:3000"
    env_file: .env
    depends_on: 
      - prismadbpostgres
    volumes:
      - prisma-app-postgres:/var/lib/prisma/app/postgres

  prismadbpostgres:
    container_name: prisma.db.postgres
    image: "postgres:14.5"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testdb"
    volumes:
      - prisma-db-postgres:/var/lib/prisma/postgres
      - ./libs/core/src/db/postgres/testdb.sql:/docker-entrypoint-initdb.d/setup-postgres.sql
volumes:
  prisma-db-postgres:
  prisma-app-postgres: